/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminLoginScreen.java
 *
 * Created on 9 May, 2011, 9:45:35 PM
 */
package com.neo.nrk.ui.admin;

import javax.swing.JOptionPane;

import com.neo.nrk.persistence.dao.AdminDao;
import com.neo.nrk.persistence.dao.AdminDaoBean;

/**
 * 
 * @author nrkkalyan
 */
public class AdminLoginScreen extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	// private final JFrame mParentScreen;
	private final AdminSettingsForm mAdminsurveySettings = new AdminSettingsForm();
	private final AdminDao mAdminDao = new AdminDaoBean();

	/** Creates new form AdminLoginScreen */
	public AdminLoginScreen() {
		// mParentScreen = parentFrame;
		setDefaultCloseOperation(EXIT_ON_CLOSE);
		initComponents();
		this.setLocationRelativeTo(getRootPane());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel2 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		passwordTextBox = new javax.swing.JPasswordField("admin");
		jLabel1 = new javax.swing.JLabel();
		cancelButton = new javax.swing.JButton();
		okButton = new javax.swing.JButton();
		userNameTextBox = new javax.swing.JTextField("admin");
		jLabel4 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("MOS tool");
		setMinimumSize(new java.awt.Dimension(588, 324));
		setResizable(false);

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Admin mode"));
		jPanel2.setAutoscrolls(true);
		jPanel2.setPreferredSize(new java.awt.Dimension(750, 600));

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel2.setText("Password");

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel1.setText("Username");

		cancelButton.setFont(new java.awt.Font("Tahoma", 1, 14));
		cancelButton.setText("Cancel");
		cancelButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelButtonActionPerformed(evt);
			}
		});

		okButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		okButton.setText("OK");
		okButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				okButtonActionPerformed(evt);
			}
		});

		userNameTextBox.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				userNameTextBoxActionPerformed(evt);
			}
		});

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel4.setText("Admin must need to login to configure the survey settings");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGap(78, 78, 78)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGap(42, 42, 42)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																						.addGroup(
																								jPanel2Layout
																										.createSequentialGroup()
																										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87,
																												javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(okButton).addGap(1, 1, 1)
																										.addComponent(cancelButton))
																						.addGroup(
																								jPanel2Layout
																										.createSequentialGroup()
																										.addGroup(
																												jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																														.addComponent(jLabel1).addComponent(jLabel2))
																										.addGap(18, 18, 18)
																										.addGroup(
																												jPanel2Layout
																														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(userNameTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 155,
																																Short.MAX_VALUE)
																														.addComponent(passwordTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 155,
																																Short.MAX_VALUE)))).addGap(91, 91, 91))
														.addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 375,
																javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(103, 103, 103)));

		jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] { cancelButton, okButton });

		jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] { passwordTextBox, userNameTextBox });

		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel2Layout
						.createSequentialGroup()
						.addGap(23, 23, 23)
						.addComponent(jLabel4)
						.addGap(49, 49, 49)
						.addGroup(
								jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(userNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(passwordTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(60, 60, 60).addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(okButton).addComponent(cancelButton))
						.addContainerGap(45, Short.MAX_VALUE)));

		jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] { passwordTextBox, userNameTextBox });

		jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] { jLabel1, jLabel2 });

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap().addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap().addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jPanel2.getAccessibleContext().setAccessibleName("");

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void userNameTextBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_userNameTextBoxActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_userNameTextBoxActionPerformed

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelButtonActionPerformed
		System.exit(0);
	}// GEN-LAST:event_cancelButtonActionPerformed

	private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_okButtonActionPerformed
		try {
			validateMinimalInputs();
			authenticateLogin();
			mAdminsurveySettings.setVisible(true);
			this.setVisible(false);
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
		}
		// TODO add your handling code here:
	}// GEN-LAST:event_okButtonActionPerformed

	private void authenticateLogin() throws Exception {
		mAdminDao.authenticate(userNameTextBox.getText(), passwordTextBox.getPassword());
	}

	private void validateMinimalInputs() throws Exception {
		// Validate if username is entered
		if (userNameTextBox.getText().trim().isEmpty()) {
			throw new Exception("Please enter the admin username.");
		}
		// Validate if password is entered
		if (passwordTextBox.getPassword().length <= 0) {
			throw new Exception("Please enter the password.");
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton cancelButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JButton okButton;
	private javax.swing.JPasswordField passwordTextBox;
	private javax.swing.JTextField userNameTextBox;
	// End of variables declaration//GEN-END:variables
}
